export const RESET = "BOOK_UPDATE_RESET";
export const SET_ERROR = "BOOK_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "BOOK_UPDATE_SET_RETRIEVED";
export const SET_HUB_URL = "BOOK_UPDATE_SET_HUB_URL";
export const SET_UPDATED = "BOOK_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "BOOK_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "BOOK_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "BOOK_UPDATE_UPDATE_RETRIEVED";
