export const BOOK_DELETE_RESET = "BOOK_DELETE_RESET";
export const BOOK_DELETE_SET_ERROR = "BOOK_DELETE_SET_ERROR";
export const BOOK_DELETE_SET_DELETED = "BOOK_DELETE_SET_DELETED";
export const BOOK_DELETE_MERCURE_SET_DELETED =
  "BOOK_DELETE_MERCURE_SET_DELETED";
export const BOOK_DELETE_TOGGLE_LOADING = "BOOK_DELETE_TOGGLE_LOADING";
