export const BOOK_CREATE_RESET = "BOOK_CREATE_RESET";
export const BOOK_CREATE_SET_CREATED = "BOOK_CREATE_SET_CREATED";
export const BOOK_CREATE_SET_ERROR = "BOOK_CREATE_SET_ERROR";
export const BOOK_CREATE_SET_VIOLATIONS = "BOOK_CREATE_SET_VIOLATIONS";
export const BOOK_CREATE_TOGGLE_LOADING = "BOOK_CREATE_TOGGLE_LOADING";
