export const BOOK_SHOW_RESET = "BOOK_SHOW_RESET";
export const BOOK_SHOW_SET_ERROR = "BOOK_SHOW_SET_ERROR";
export const BOOK_SHOW_SET_RETRIEVED = "BOOK_SHOW_SET_RETRIEVED";
export const BOOK_SHOW_SET_HUB_URL = "BOOK_SHOW_SET_HUB_URL";
export const BOOK_SHOW_TOGGLE_LOADING = "BOOK_SHOW_TOGGLE_LOADING";
