name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create build
      run: |
        zip -r build.zip .     

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.PASSWORD }}
        #KEY: ${{ secrets.SSHKEY }}
      with:
        source: "build.zip"
        target: "/root"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.PASSWORD }}
        #KEY: ${{ secrets.SSHKEY }}
        script: |
          unzip -o Challenge-Vue-ApiPlatform.zip
          cd build
          npm install
          npm run build
          cd ..
          docker-compose up -d
