name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: |
        zip -r Challenge-Vue-ApiPlatform.zip . -x ".git/*" ".github/*" 

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.PASSWORD }}
        #KEY: ${{ secrets.SSHKEY }}
      with:
        source: "Challenge-Vue-ApiPlatform.zip"
        target: "/root"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.PASSWORD }}
        #KEY: ${{ secrets.SSHKEY }}
        script: |
          unzip -o /root/Challenge-Vue-ApiPlatform.zip
          cd /root/Challenge-Vue-ApiPlatform/vuejs
          npm install
          npm run build
          cd ..
          docker-compose up -d
